all:
  children:
    nxos:
      hosts:
        nxos-sw01:
        nxos-sw02:
        nxos-sw03:
        nxos-sw04:
        nxos-sw05:
        nxos-sw06:
        nxos-sw07:
        nxos-sw08:
    ios:
      hosts:
        ios-sw01:
        ios-sw02:
    netscaler:
      hosts:
        netscaler-sw01:
        netscaler-sw02:
