[windows_sql]
win-sql-01 ansible_host=win-sql-01.example.com ansible_user=Administrator ansible_password=YourPasswordHere ansible_connection=winrm ansible_winrm_transport=ntlm ansible_winrm_server_cert_validation=ignore
win-sql-02 ansible_host=win-sql-02.example.com ansible_user=Administrator ansible_password=YourPasswordHere ansible_connection=winrm ansible_winrm_transport=ntlm ansible_winrm_server_cert_validation=ignore
