---
- name: Build IOS POSTTASK commands
  ansible.builtin.set_fact:
    commands: "{{ ios_check_cmds }}"

- name: Run IOS POSTTASK commands
  cisco.ios.ios_command:
    commands: "{{ commands }}"
  register: post

- name: Write IOS POSTTASK CSV
  vars:
    csv_file: "{{ snapshot_dir }}/posttask_{{ run_ts }}.csv"
    csv_column: "posttask_{{ run_ts }}"
    results_list: "{{ post.stdout }}"
  import_tasks: "../../common_csv/tasks/append_phase_csv.yml"
