---
- name: Copy esxi_precheck.ps1
  win_copy:
    src: esxi_precheck.ps1
    dest: "C:\\Temp\\esxi_precheck.ps1"

- name: Run ESXi precheck
  win_shell: |
    powershell.exe -ExecutionPolicy Bypass "C:\\Temp\\esxi_precheck.ps1" `
      -vcenter "{{ vcenter_hostname }}" `
      -username "{{ vcenter_username }}" `
      -password "{{ vcenter_password }}" `
      -host "{{ esxi_host }}"
  register: precheck_out

- debug:
    var: precheck_out.stdout_lines

- name: Cleanup
  win_file:
    path: "C:\\Temp\\esxi_precheck.ps1"
    state: absent
