---
- name: Copy inventory script
  win_copy:
    src: get_inventory.ps1
    dest: "{{ temp_script_path }}\\get_inventory.ps1"

- name: Query vCenter inventory
  win_shell: |
    powershell.exe -ExecutionPolicy Bypass "{{ temp_script_path }}\\get_inventory.ps1" `
      -vcenter "{{ vcenter_hostname }}" `
      -username "{{ vcenter_username }}" `
      -password "{{ vcenter_password }}"
  register: inv_out

- debug:
    var: inv_out.stdout_lines

- name: Cleanup
  win_file:
    path: "{{ temp_script_path }}\\get_inventory.ps1"
    state: absent
